### ISSUE TITLE
--execute also executes @@@CODE imports

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#125]
As `@@@CODE` directives result in the imported code being placed inside a `!bc` - `!ec` block, when `--execute` is used, these code blocks are also executed, at least in `.ipynb` and `.html` outputs. This may be a desired result.

However, I sometimes use `@@@CODE` to show the content of a `.csv` file, and then 'code execution' is undesired (it often leads to a Python error, in my case). 

Regardless of my use case, perhaps `@@@CODE` could have a `-t` equivalent?

**Comment by lexnederbragt** [comment]
To reproduce: use https://github.com/lexnederbragt/doconce_demo/blob/master/include1, compile `include1.do.txt`to various formats. Note that for some reason `.ipynb` is not affected, which may be considered a bug...

**Comment by aless80** [comment]
I agree that `@@@CODE` used to copy text files should not be executed. 

I also understand that you might want more flexibility in the behavior of `@@@CODE` when [Copying Code from Source Files](https://doconce.github.io/doconce/doc/pub/manual/manual.html#copying-code-from-source-files) , e.g. to be able to apply postfixes such as `-t`. Maybe I can try to develop some syntax as follows: 
```
!bc pycod -t
@@@CODE ../code/code1.py
!ec
```


In any case what should the default behavior be of `@@@CODE` when `--execute` is used? Execute, print out, or something else?

--------

About your second comment: I think it boils down to: 
```
Here is some plain text.

Now we add some python code with output:

@@@CODE ../code/code1.py

!bc pyout
55
!ec
```

If you remove the `pyout` cell, I think it works (`doconce format html --execute`). Maybe I do not see what you want to achieve, but it actually sounds better to me because you do not hard code the output of the calculation.

**Comment by lexnederbragt** [comment]
I would say the default behavior be of `@@@CODE` when `--execute` is used would be execute. Is there anything against `@@@CODE-t`as a new thing?

**Comment by aless80** [comment]
I think this is already implemented, see [Copying Code from Source Files](https://doconce.github.io/doconce/doc/pub/manual/manual.html#copying-code-from-source-files), second example.

In the first and second boxes the docs should mention the whole syntax (which I defined as `!bc LANG[cod|pro][postfix]`) including the postfix, for example:

```
@@@CODE somefile.py envir=LANG[cod|pro][postfix]
```

**Comment by lexnederbragt** [comment]
Ah, I see. The solution to my problem seems to be to use `@@@CODE ../data/exp_growth.csv envir=None` in https://github.com/lexnederbragt/doconce_demo/blob/main/src/do_files/code1_nocode.do.txt. However, when I do that (with the latest DocOnce version, commit e9ce1723), I still get the same `NameError` in `include1.pdf` ...

**Comment by aless80** [comment]
I am not sure what `include1.pdf` is, nor `NameError`. I am not sure what commands you are using.

This is based on your code and it looks good to me. I haven't really read what that `doconce ptex2tex issue125 envir=ans:nt` below means. 

```
doconce format html issue125.do.txt --execute
# or
doconce format latex issue125.do.txt --execute
doconce ptex2tex issue125 envir=ans:nt
pdflatex -shell-escape issue125.tex
```

DocOnce code in `issue125.do.txt`:
```
Python code, just text

@@@CODE ../code/code1.py envir=py-t

Here is some plain text.

Now we add some python code with output:

@@@CODE ../code/code1.py envir=pycod

And some data

@@@CODE ../data/exp_growth.csv envir=csv
```

**Comment by lexnederbragt** [comment]
No worries, in my test cases all is well now. Using `envir=csv` is my solution. (`=None` works also). Thanks!
