### ISSUE TITLE
Enable TOC in ipynb

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#188]
Could `TOC:on` be made to work with ipynb also?

**Comment by lexnederbragt** [comment]
Hmm, I see a TOC at the top, but the links do not lead to the sections. This seems to be because the anchor tags are not present in relevant cells of the notebook...?

Also, could there be added an `<p>` (empty line) between `<h1 id="table_of_contents">Table of contents</h1>` and <div `class='toc'>`?

**Comment by aless80** [comment]
The TOC works for me. I think there is an empty line after that `<h1>` tag, but not with `<p>`. Please check again

**Comment by lexnederbragt** [comment]
Now it works for me too.

As for the extra empty line: currently, with a blank lin in the markdown cell, 

```
<h1 id="table_of_contents">Table of contents</h1>

<div class='toc'>
<p><a href="#Plain-text"> Plain text </a></p>
...
...
```


it renders as

<img width="286" alt="image" src="https://user-images.githubusercontent.com/1122351/149287210-8267a54e-1637-4e6a-a3a9-89d289823828.png">

With an extra `<p>` 

```
<h1 id="table_of_contents">Table of contents</h1>
<p>
<div class='toc'>
<p><a href="#Plain-text"> Plain text </a></p>
...
...
```

it looks a bit better:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/1122351/149287278-7a98af34-c889-4342-b80c-93f1b3c61fb0.png">

**Comment by aless80** [comment]
That come because of different CSS margin property of `<h1>`tags in html (margin=19.296) vs ipynb (margin=0). That property is some default in the browser (Chrome flags it with "user agent stylesheet") which is overridden by Less settings in Jupyter Notebook. 

I am not sure what is the most elegant solution. 
1) Adding  `<p></p>` in both html and ipynb would work but is IMO very ugly. There might still be regex in DocOnce removing these empty paragraph tags;
2) Hard coding the margin in the tag as for example `<h1 id="table_of_contents"  style="margin:0.67em 0 0.67em 0;">Table of contents</h1>`;
3) Adding CSS style to the notebook or fixing CSS/Less in Jupyter Notebook.

**Comment by aless80** [comment]
Continue in issue #226
