### ISSUE TITLE
New feature: abort on error with --execute

### ISSUE THREAD

**Issue by lexnederbragt** [doconce/doconce#193]
This is an idea for a new feature:

1) when running with `--execute`, enable a `--execute_abort_on_error` flag (or a better name) that causes the conversion to abort when the execution of the code throws an(y) error
2) add a new postfix to `!bc LANG[cod|pro][postfix]`, for example `-err', that causes any error thrown by that block to be ignored by the new flag from 1), and the result of the error to be part of the output (as is the case now)

The idea is: with 1), optionally making sure code is executed without errors, eliminating need for a manual check afterwards. With 2), when a doconce file contains a deliberate error, allow it (e.g., for teaching purposes).

**Comment by aless80** [comment]
Is the current default (show the error in the output, no abort) ok?  
It is not enough to print out a warning when some executed code errors out, is it?  

More in general I am thinking of reusing options to optionally take arguments, such as `--execute=abort` for `--execute_abort_on_error`, instead of having to create new options. Do you think that is a good idea?

**Comment by lexnederbragt** [comment]
Current default is OK. Printing out a warning helps, but I'd rather have the option to have things crash to a halt, also because when using `make` to compile many documents, it will tell you that something went wrong, you can then fix the error and simply run `make` again.

Your suggestion for expanding existing arguments rather than adding new ones sounds very good!

**Comment by aless80** [comment]
Pull request #202 should implement what suggested in point 1, but using the option `--execute=abort`. 

Point 2: the issue is that currently only one postfix is allowed, as the behaviors for the current ones exclude any other. This is probably not the case for `-err`. I will have to re-implement several parts of the code.  
I am also thinking of having all postfixes start with a dash, i.e. change `out` and `hid` to `-out` and `-hid`.

**Comment by aless80** [comment]
Pull request #203 should implement point 2. Now there syntax for code is: 
```
!bc LANG[cod|pro][POSTFIX][-err]
```
where `POSTFIX` is one of `-t`,`-out`,`-e`,`-h`,`-hid` and `-err` is the one asked in point 2 above. Notice that I changed  `hid` and `out` to `-hid` and `-out` so that they are more consistent, but the old  `hid` and `out` should still work. 

I had to rework a substantial part of the code in `ipynb.py`. I hope everything works as before and the tests are fine.

I am wondering if the `-e` postfix is really needed: this postfix hides code as `-hid` but for the `ipynb` format, whereas `-hid` just collapses the cell in `ipynb`.

**Comment by lexnederbragt** [comment]
My first tests shows that this indeed works as expected. Thanks!

**Comment by lexnederbragt** [comment]
The difference between `-hid` and `-e` is, as far as I understand it, that `-hid` allows code to be hidden (but executed) in other formats, but visible (and executed) in ipynb. The ensures that when someones reruns the notebook, the code runs as expected. 

A use case for `-e` is from the book I am cowriting:

At the top of the doconce file, have

```
!bc pycod-e
import os
this_is_a_tmp_variable_that_never_should_be_used_in_our_code_1 = os.getcwd()
os.chdir("folder_with_datafiles")
!ec
```

At the bottom of the notebook, have

```
!bc pycod-e
os.chdir(this_is_a_tmp_variable_that_never_should_be_used_in_our_code_1)
!ec
```

This allows execution of the notebok in a different folder than the doconce file, in this case the folder with the datafiles. These datafiles can then be kept separate from the doconce file. 

By the way, this is what inspired #195.

**Comment by lexnederbragt** [comment]
By the way, if it is not too complicated, a small request: 

When compiling with `--execute`, and getting an error, write down a warning to the screen:

`Warning: found error in code block:`

When compiling with `--execute=abort`, and getting an error, write down an error to the screen:

`*** error: Error in code block:`

This is (I think) in line with how doconce writes doen warnings for other things that do not cause an abort.
