### ISSUE TITLE
Fix the sphinx documentation

### ISSUE THREAD

**Issue by aless80** [doconce/doconce#26]
Fix the sphinx documentation, which is not formatted properly (eg [manual](https://doconce.github.io/doconce/doc/pub/manual/html/index.html))

**Comment by MartinHeroux** [comment]
Hi Allesandro, I have been a fan of Doconce for a long time. 

I made minor commits to the tutorial documents that were merged by HPL. I always wished I could contribute more, but the code-base is well beyond my Python skills. Having said that, I would love to be able to contribute and slowly learn more about the codebase. As such, I am happy to look into this issue if you can provide me with all little guidance.

**Comment by aless80** [comment]
Hi Martin,
Good to hear that you like DocOnce. I send you a private message, so that we can discuss

> Hi Allesandro, I have been a fan of Doconce for a long time.
> 
> I made minor commits to the tutorial documents that were merged by HPL. I always wished I could contribute more, but the code-base is well beyond my Python skills. Having said that, I would love to be able to contribute and slowly learn more about the codebase. As such, I am happy to look into this issue if you can provide me with all little guidance.

**Comment by mimeiners** [comment]
Hello Alessandro!
Hello Martin!

Sphinx implementation in doconce is an always open-topic, since Sphinx itself changed drastically the wrappers from version to version, which doconce uses.
I started discussing this issue with Hans-Petter and continued with Kristian. My last status is that Kristian and I discussed to implement Sphinx via an API instead of calling the quick-build wrapper. I have already opened branches in hpl's repo and contributed my findings into the master branch.
My current understanding is that Sphinx, I mean the wrapper, builds a dictionary 'd' from the questions; doconce answers theses questions. This entry point is quite vulnerable. We might build the necessary dictionary 'd' inside doconce and call sphinx build process directly.

So, maybe we can sumup our Sphinx forces ;o)

By the way, it is great, that you, Alessandro, carry on maintaining doconce.
I really appreciate this.


Best regards

Mirco
